from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_community.document_loaders import TextLoader
from langchain_ollama import ChatOllama
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from langchain_core.prompts import PromptTemplate
import gradio as gr
from langchain_ollama import OllamaEmbeddings

embeddings = OllamaEmbeddings(
    model="hf.co/mixedbread-ai/mxbai-embed-large-v1:F16"
)

# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

llm = ChatOllama(
    model="qwen3",
    temperature=0,
    num_predict=256,
    sync_client_kwargs={"timeout": 120},
)


def document_loader(file):
    loader = TextLoader(file.name)
    return loader.load()

def text_splitter(data):
    return RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=50, length_function=len).split_documents(data)

def vector_store(data):
    return Chroma.from_documents(data, embeddings)

def retriver(file):
    data = document_loader(file)
    texts = text_splitter(data)
    vector_db = vector_store(texts)
    retriver = vector_db.as_retriever()
    return retriver

prompt = PromptTemplate.from_template("""
Answer the question based only on the context.

Context:
{context}

Question:
{question}
                            
return the ouput as a string
""")

chain = prompt | llm | StrOutputParser()

def chain_call(file, question):

    retriever_obj = retriver(file)
    context_docs = retriever_obj.invoke(question)[:2]

    texts = [doc.page_content for doc in context_docs]
    input_data = {
        "context": "\n\n".join(texts),
        "question": question,
    }

    input_data = {
        "context": "\n\n".join(texts),
        "question": question,
    }
    return chain.invoke(input_data)

rag_application = gr.Interface(
    fn=chain_call,
    inputs=[
        gr.File(label="Upload txt File", file_count="single", file_types=['.txt'], type="filepath"),  # Drag and drop file upload
        gr.Textbox(label="Input Query", lines=2, placeholder="Type your question here...")
    ],
    outputs=gr.Textbox(label="Output"),
    title="RAG Chatbot",
    description="Upload a PDF document and ask any question. The chatbot will try to answer using the provided document."
)

# Launch the app
rag_application.launch(server_name="0.0.0.0", server_port=7860, share=True)